### ISSUE TITLE
require.js or server equivalent missing in build

### ISSUE THREAD

**Issue by vsoch** [brown-ccv/honeycomb#23]
I've added a script `expfactory-it` and a container (Dockerfile) that will generate the static assets into a folder of interest, default is the `/data` folder in the container. I'm first testing the static files as is, and it looks like require.js (or it's server equivalent) is missing:

```
jspsych.js?a627:45 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
eval @ jspsych.js?a627:45
photodiode.js:9 Uncaught TypeError: window.require is not a function
    at Module.<anonymous> (photodiode.js:9)
    at a ((index):1)
    at Object.<anonymous> (main.09070895.chunk.js:1)
    at a ((index):1)
    at i ((index):1)
    at Array.e [as push] ((index):1)
    at main.09070895.chunk.js:1
manifest.json:1 Failed to load resource: the server responded with a status of 404 (File not found)
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
:9999/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (File not found)
```
The basic steps for the build are:
```bash
npm run build
mkdir -p ${EXPORT_DIR}/static/lib
cp -R ${ROOT}/build/static/* $EXPORT_DIR/static/
cp ${ROOT}/build/*.js* ${EXPORT_DIR}/static/
cp ${ROOT}/build/lib/*.js ${EXPORT_DIR}/static/lib/
cp ${ROOT}/build/index.html $EXPORT_DIR/index.html
echo "Exported files are in $EXPORT_DIR"
```
We would want to have a build that includes all javascript dependencies. Is this possible?

**Comment by vsoch** [comment]
I pushed the branch if you'd like to see it!

https://github.com/researchapps/neuro-task-starter/tree/add/Dockerfile

The goal is to have a fully working static export, and then we can test for deployment with expfactory.

**Comment by mcmcgrath13** [comment]
Right now the task is set up for two main cases: on electron, and in MTurk and because this code isn't running on MTurk, it thinks it should be in electron-land.  I'll work on abstracting that, but for the moment in `src/config/main.js` if you hardcode `const MTURK = true` on line 20, then that should get around this issue for the time being.

**Comment by vsoch** [comment]
Woot! That did the trick!

![image](https://user-images.githubusercontent.com/814322/70840200-f68a9580-1dcd-11ea-9e46-f572b2acc0d5.png)

I updated the branch with the changes - it came down to using sed in the Dockerfile (imperfect but works!) I should be able to look more into the submit / next issue this weekend.
