### ISSUE TITLE
Tag for paper revision

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/honeycomb#60]
We may all want to sync, but from what I gather, this is the wishlist for the final version:

- [ ] Merge #36 @Rashi1997 after few edits from feedback
- [x] Merge and #58  after verifying behavior
- [ ] Attention checks @Rashi1997 
- [x] Claryfing which installers run when. I think documentation needs a CI section @mirestrepo 
- [ ] Moving documentation into the new docs - single source of truth 
- [ ] More introduction and few diagrams in the docs @nicoleprovenza 
- [ ] A more rich sample task @nicoleprovenza

**Comment by nicoleprovenza** [comment]
additional items to discuss: 
- [x] add 'home' installers to CI workflow (tasks with no events)
- [ ] rename saved data folder

**Comment by mirestrepo** [comment]
Paper version is the V1.X series
