### ISSUE TITLE
Bring changes from online tasks to honeycomb

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/honeycomb#79]
- [x]  Refactor login
- [x] Refactor ENVs
- [x] Instructions for Firebase actions
- [ ] Bring config changes per participant

**Comment by galenwinsor** [comment]
@mirestrepo Do we want to bring that last change into Honeycomb? If so, I can do that, but I had thought we only wanted it in Beads.

**Comment by mirestrepo** [comment]
@galenwinsor I think you are correct- that's only for beads. @mcmcgrath13 correct? this is where you explained to me that is not something very generalizable to all tasks at the moment?
If I recall, Mary said that in the honeycomb docs we could point to beads as an explamble on how to achieve this behavior

**Comment by mcmcgrath13** [comment]
Yeah, I don't think this is generic enough for honeycomb at this point.  Add something to docs to talk about it as an option and point to beads as an example.
